rest-authentication/rest/urls.py

from django.contrib import admin
from django.urls import path, include
from .router import router
from rest_framework.authtoken import views
from django.contrib.auth.views import login

urlpatterns = [
    path('snippets/', include('snippets.urls', namespace='snippets')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('login/', login, name='login')
]

rest-authentication/snippets/urls.py

from django.urls import path, include
from . import views

app_name = 'snippets'
urlpatterns = [
    path('', views.SnippetListView.as_view(), name='list'),
    path('<int:pk>/', views.SnippetDetailView.as_view(), name='detail')
]

rest-authentication/snippets/models.py
from django.db import models


class Snippet(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

rest-authentication/snippets/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Snippet
from django.views import View
from django.views.generic import ListView, DetailView


class SnippetListView(ListView):
    model = Snippet
    template_name = 'snippets/snippet_list.html'


class SnippetDetailView(DetailView):
    model = Snippet
    template_name = 'snippets/snippet_detail.html'

rest-authentication/snippets/templates/snippets/snippet_detail.html
{% extends 'base.html' %}

{% block title %}Snippet Detail{% endblock title %}

{% block content %}

<h1>{{ snippet.title }}</h1>

<pre>
  {{ snippet.body_preview }}
</pre>

{% endblock content %}

rest-authentication/snippets/templates/snippets/snippet_list.html
{% extends 'base.html' %}

{% block title %}Snippet List{% endblock title %}

{% block content %}

<ul>
  {% for snippet in snippet_list %}
    <li>
      <a href="{% url 'snippets:detail' snippet.id %}">{{ snippet.title }}</a>
    </li>
  {% endfor %}
</ul>

{% endblock content %}